[env]
patch_dir = "../patches"
branch = "release/v1.22"
repo = "https://github.com/go-gitea/gitea"
# use commit 578c02d6529a589dfa5470462e8ca9ab5fa4a5fc

[project]
name = "pkg.ci"
version = "0.3.0"

[tasks]
clean.script = "rm -rf gitea"
reset.script = "bash -c 'git -C gitea reset --hard HEAD && git -C gitea clean -fd'"
clone.script = ["maid clean -q", "git clone -b %{env.branch} --single-branch %{env.repo}"]

[tasks.patch]
path = "gitea"
script = [
  "git apply --reject --whitespace=nowarn %{env.patch_dir}/gitea.patch",
  "git apply --reject --whitespace=nowarn %{env.patch_dir}/navbar.patch"
]

[tasks.build]
path = "gitea"
depends = ["patch"]
script = "bash -c 'TAGS=\"bindata sqlite sqlite_unlock_notify\" make build'"

[tasks.install]
path = "gitea"
script = ["service gitea stop", "cp gitea /home/gitea", "service gitea start", "rm gitea"]
